In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [5]:
!mkdir ~/.kaggle


mkdir: cannot create directory ‘/root/.kaggle’: File exists


In [6]:
!cp /content/drive/MyDrive/LearnAboutTfrecord/First/cars.tfrecords ~/.kaggle/

In [7]:
!chmod 600 ~/.kaggle/cars.tfrecords

In [13]:
import tensorflow as tf

def get_feature_description():
  feature_description = {
      'region': tf.io.FixedLenFeature([], tf.string),
      'price': tf.io.FixedLenFeature([], tf.int64),
      'year': tf.io.FixedLenFeature([], tf.float32),
      'fuel': tf.io.FixedLenFeature([], tf.string),
      'odometer': tf.io.FixedLenFeature([], tf.float32),
      'lat': tf.io.FixedLenFeature([], tf.float32),
      'type': tf.io.FixedLenFeature([], tf.string)
  }
  return feature_description

def parse_example(record):
  return tf.io.parse_single_example(record, get_feature_description())

cars_dataset = tf.data.TFRecordDataset("/content/drive/MyDrive/LearnAboutTfrecord/First/cars.tfrecords")
parsed_tfrecords = cars_dataset.map(map_func=parse_example)



In [14]:
parsed_tfrecords

<_MapDataset element_spec={'fuel': TensorSpec(shape=(), dtype=tf.string, name=None), 'lat': TensorSpec(shape=(), dtype=tf.float32, name=None), 'odometer': TensorSpec(shape=(), dtype=tf.float32, name=None), 'price': TensorSpec(shape=(), dtype=tf.int64, name=None), 'region': TensorSpec(shape=(), dtype=tf.string, name=None), 'type': TensorSpec(shape=(), dtype=tf.string, name=None), 'year': TensorSpec(shape=(), dtype=tf.float32, name=None)}>

In [15]:
for i in parsed_tfrecords.take(5):
  print(i)

{'fuel': <tf.Tensor: shape=(), dtype=string, numpy=b'gas'>, 'lat': <tf.Tensor: shape=(), dtype=float32, numpy=32.59>, 'odometer': <tf.Tensor: shape=(), dtype=float32, numpy=57923.0>, 'price': <tf.Tensor: shape=(), dtype=int64, numpy=33590>, 'region': <tf.Tensor: shape=(), dtype=string, numpy=b'auburn'>, 'type': <tf.Tensor: shape=(), dtype=string, numpy=b'pickup'>, 'year': <tf.Tensor: shape=(), dtype=float32, numpy=2014.0>}
{'fuel': <tf.Tensor: shape=(), dtype=string, numpy=b'gas'>, 'lat': <tf.Tensor: shape=(), dtype=float32, numpy=32.59>, 'odometer': <tf.Tensor: shape=(), dtype=float32, numpy=71229.0>, 'price': <tf.Tensor: shape=(), dtype=int64, numpy=22590>, 'region': <tf.Tensor: shape=(), dtype=string, numpy=b'auburn'>, 'type': <tf.Tensor: shape=(), dtype=string, numpy=b'pickup'>, 'year': <tf.Tensor: shape=(), dtype=float32, numpy=2010.0>}
{'fuel': <tf.Tensor: shape=(), dtype=string, numpy=b'gas'>, 'lat': <tf.Tensor: shape=(), dtype=float32, numpy=32.59>, 'odometer': <tf.Tensor: shap